import Head from "next/head";

import { RegisterForm } from "@components";
import { Box } from "@mui/material";

const Home = () => {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box display="flex" width="100%" justifyContent="center">
          <RegisterForm />
        </Box>
      </main>
    </>
  );
};

export default Home;
