import Head from "next/head";

import RegisterForm from "../src/components/RegisterForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RegisterForm />
      </main>
    </>
  );
}
